---
 - name: git clone anyenv
   git: repo="https://github.com/riywo/anyenv" dest=~/.anyenv accept_hostkey=yes

 - name: anyenv install init
   shell: >-
     if ! [ -e "{{ ansible_env.HOME  }}/.config/anyenv/anyenv-install" ] ; then
       echo y | $HOME/.anyenv/bin/anyenv install --init ;
     fi

 - name: install *env
   shell: >-
     source ~/.zshenv ;
     if ! [ -e "{{ ansible_env.HOME  }}/.anyenv/envs/{{ item }}" ] ; then
       anyenv install "{{ item }}" ;
     fi
     executable=/bin/zsh
   with_items: "{{ envs }}"
   vars:
     envs:
        - "rbenv"
        - "nodenv"
        - "pyenv"

