---
 - name: change shell
   user:
     name: "{{ ansible_env.USER }}"
     shell: "/bin/zsh"
   become: yes

 - name: add PATH to .zshenv
   blockinfile:
     dest: ~/.zshenv
     block: |
       # for homebrew
       eval "$(/opt/homebrew/bin/brew shellenv)"
       # for asdf
       . $(brew --prefix asdf)/asdf.sh
       # for direnv
       export EDITOR=vi
       eval "$(direnv hook zsh)"
       # for exa
       alias ls='exa --time-style=long-iso -g'
       alias ll='ls --git --time-style=long-iso -gl'
       alias la='ls --git --time-style=long-iso -agl'
       alias l1='exa -1'
       # for ripgrep
       alias grep="rg"
       # for zoxide
       eval "$(zoxide init zsh)"
       alias zq="zoxide query"
