---
 - name: Setting initial key repeat
   osx_defaults:
     key: InitialKeyRepeat
     type: int
     value: 10

 - name: Setting key repeat time
   osx_defaults:
     key: KeyRepeat
     type: int
     value: 1
